### PR TITLE
Python plotting for the ocean/wave 

### PR DESCRIPTION
**Pull request by JessicaMeixner-NOAA**
- plotting MOM6 fields from native tripolar grid
- plotting diff of MOM6 fields from native tripolar grid
- plotting diff of MOM6 to data (OSTIA,MLD) from grib2 ocnice files converted to netcdf
- plotting of WW3 fields

This is the first iteration of these routines. They have been successfully run on hera
using the following:
module use -a /scratch2/NCEPDEV/marineda/Jong.Kim/save/modulefiles/
module load anaconda/3.15.1

Thanks to @LydiaStefanova-NOAA for data pre-processing and to the MDAB-DA group who's python scripts
were used as templates for getting started!

### CODE REVIEW

**Comment by JessicaMeixner-NOAA** [comment]
@LydiaStefanova-NOAA  I tried to follow the structure of the other folders as much as possible.  Please let me know if this folder structure is acceptable, readme's need more information, etc.

**Comment by LydiaStefanova-NOAA** [comment]
@JessicaMeixner-NOAA  

Thank you for adding these, they are great! The folder structure looks good to me. 

Having so far looked only at the OCN scripts: 

./plot_mom6.py and ./plot_mom6_diff.py work without a hitch.

For ./plot_mom6_diff_ostia.py
--  I think line 65 (data = data2[1:,:] - data1) should be  data = data2 - data1. As it is, it runs if the obs are at 1440x720 and the model at 1440x721 (but is off by one half of the size of a grid point) but fails if both the obs and the model are at 1440x721. 
-- Also suggest replacing the "-m" argument for varminmaxval with "-vm" to match the other three OCN scripts

Similarly in ./plot_mom6_diff_mlddata.py:
--  Unless line 66 is replaced with data = data2 - data1 the obs are expected to have one less latitude than the model and it doesn't work if both are at the same resolution. The example file (/scratch2/NCEPDEV/climate/Jessica.Meixner/Data/analysis/MLD/mld_DR003_c1m_reg2.0.nc) is 180x90 and the instructions are to nco regrid the model to 180x91, so the code works, but the results are half a grid point off. 
-- May be helpful to add a clarification that the variable specified with -v refers to the variable name in the obs and not the model (and/or perhaps give it a hardwired default like you did for the sst in ./plot_mom6_diff_ostia.py ?)

Unless there are considerations against, it would be helpful to have in the README the module information you listed here 
(module use -a /scratch2/NCEPDEV/marineda/Jong.Kim/save/modulefiles/
module load anaconda/3.15.1)

**Comment by JessicaMeixner-NOAA** [comment]
@LydiaStefanova-NOAA  I have updated the READMEs and usages based on your review above. 

Line 66 of plot_mom6_diff_ostia.py should be  data = data2 - data1 (this was a bug, putting what should be in mld into Ostia, thanks for catching!) 

For,  plot_mom6_diff_mlddata.py, I think we want to leave things as is, because the obs as given do have 1 less dimension than the model output.  Using the code as is but adding: 
    print(np.shape(lats))
    print(lats)
    print(np.shape(lats2))
    print(lats2[1:])
If you run: 
./plot_mom6_diff_mlddata.py -i1 /scratch2/NCEPDEV/climate/Jessica.Meixner/Data/analysis/MLD/mld_DR003_c1m_reg2.0.nc -m 09 -i2 /scratch2/NCEPDEV/marine/Jessica.Meixner/DATA/p5nowavenoLT/ocn/avg/ocn_grib_2p0_avg_09.nc -t1 mld_DR003_lats -t2 p5nowavenoLT_09 -v mld -vm 1

The output is: 
(90,)
[-88.  -86.  -84.  -82.  -80.  -78.  -76.  -74.  -72.  -70.  -68.  -66.
 -64.  -62.  -60.  -58.  -56.  -54.  -52.  -50.  -48.  -46.  -44.  -42.
 -40.  -38.  -36.  -34.  -32.  -30.  -28.  -26.  -24.  -22.  -20.  -18.
 -16.  -14.  -12.  -10.   -8.   -6.   -4.   -2.    0.    2.    4.    6.
   8.   10.   12.   14.   16.   18.   20.   22.   24.   26.   28.   30.
  32.   34.   36.   38.   40.   42.   44.   46.   48.   50.   52.   54.
  56.   58.   60.   62.   64.   66.   68.   70.   72.   74.   76.   78.
  80.   82.   84.   86.   88.   89.5]
(91,)
[-88. -86. -84. -82. -80. -78. -76. -74. -72. -70. -68. -66. -64. -62.
 -60. -58. -56. -54. -52. -50. -48. -46. -44. -42. -40. -38. -36. -34.
 -32. -30. -28. -26. -24. -22. -20. -18. -16. -14. -12. -10.  -8.  -6.
  -4.  -2.   0.   2.   4.   6.   8.  10.  12.  14.  16.  18.  20.  22.
  24.  26.  28.  30.  32.  34.  36.  38.  40.  42.  44.  46.  48.  50.
  52.  54.  56.  58.  60.  62.  64.  66.  68.  70.  72.  74.  76.  78.
  80.  82.  84.  86.  88.  90.]

So we do have one difference with the 89.5 and the 90 being 1/2 degree off but otherwise, the latitudes match up how I would expect.   Ideally some sort of internal interpolation in the plotting routine to map the native tripolar grid (instead of using the grib2->netcdf) to the observation/analysis grid but working with what we have, I think we need to keep the "data = data2[1:,:]  - data1", but I still think this is worthy of checking without these additional steps.

**Comment by LydiaStefanova-NOAA** [comment]
@JessicaMeixner-NOAA 

Thanks for the edits and for the clarification about the MLD latitudes. I agree with you that given the way the MLD obs are spaced, the way you've done it is the way to go. So all the OCN scripts look good to me. 

In WAV/plots/plot_ww3nc.pyI think a typo has crept in on line 56, which is currently
dat = anc.close()
If I change it to 
datanc.close() 
the script works without a problem.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks for catching all the typos! The wave one is fixed now.

**Comment by LydiaStefanova-NOAA** [comment]
Thank you!

**Pull request merged**
