### PR TITLE
Updates for improved gross checks

### PR DESCRIPTION
**Pull request by rgrumbine**
- Adding checks against bounding curves 
- improved structure of bounds class
- cleaner code for doing wholesale gross bound checks
- extract the bounds control files (e.g. ocean.extremes) to a control (ctl) directory

Coupled modeling group presentation 5 May 2021

### CODE REVIEW

**Comment by LydiaStefanova-NOAA** [comment]
@rgrumbine 
My notes so far:

- Please add mmablib to the pull request. I used the master of https://github.com/rgrumbine/mmablib to proceed

-  In ice_scoring/makeall.sh, "module load netcdf/4.7.4" results in error message
`Lmod has detected the following error:  The following module(s) are unknown: "netcdf/4.7.4". I used "module load netcdf" instead to proceed`

- In ice_scoring/gross_checks - I have so far confirmed that I'm able to run gross_ice.py, will also check the others listed in README (gross_ocean.py, wholesale_*.py and delta_ice.py)

- The following points are outside the subject of this pull request - shall I make a separate issue for them?: in ice_scoring/master/README
   - The instructions for ice_edge don't work
`cd ice_edge; make; mv find_edge_ims cscore_edge find_edge find_edge_cice find_edge_nrl ../../exec/` 
but there is no makefile in ICE/ice_scoring/ice_edge
   - Need instructions about how to run the actual verification, i.e. which scripts need to edited and run in what order
   - Add instructions on how/where to add the fix files, e.g., if that is correct,
`in ICE/ice_scoring/
 ln -s /home/Robert.Grumbine/rgdev/fix fix`

**Comment by rgrumbine** [comment]
I've added a copy of mmablib to my develop branch

modules are always going to be a problem because of their inconsistent naming and requirements (e.g. on some platforms, you can just say module load netcdf, on others it must be the version number as well, sometimes capitalization matters). I've better-labeled the module section of makeall.sh

The ice_edge makefile is in subdirectory ice_edge/C, and is called by the makeall.sh in ice_scoring. I'm trying to avoid making people go down in to every subdirectory. For that matter, there's no need to build the mmablib; it, too, is handled by the makeall.sh. I've changed the master/README file to point to this, and am starting on the instructions/guide for use.

I've added mention of how to get the fixed fields directory to the README. You're right, it should be my fix directory via soft link. (It isn't enormous, about 1 Gb, but it's best not to have outdated versions running around.)

README in master now gives guidance on what and how to edit, and what to expect for output.

**Comment by LydiaStefanova-NOAA** [comment]
1. Gross checks work ok. 

2. For verification, the instructions are missing a step: the same modules that are in makeall.sh have to be used in running all.csh or else the netcdf libraries cannot be found. 
To get verification to run, I added in "all.csh" the same modules that are loaded in "makeall.sh", i.e., 
`module load intel/18.0.5.274`   
`module load impi/2018.4.274 `  
`module load netcdf/4.7.0 `   

3. Also, adding to "all.csh" 
`module load wgrib2`
helps get rid of an error message that wgrib2 cannot be found 

4. In all $exp...out files there is a "Logging error": see e.g. /scratch1/NCEPDEV/stmp2/Lydia.B.Stefanova/RetestBob/p6.verf/out.20110401/p6.20110401.20110402.out. What is that about? (I am guessing nothing crucial, since the code runs and produces results). Snippet below:
```
--- Logging error ---
Traceback (most recent call last):
  File "/scratch2/NCEPDEV/climate/Robert.Grumbine/anaconda3/lib/python3.7/logging/handlers.py", line 940, in emit
    self.socket.sendto(msg, self.address)
OSError: [Errno 101] Network is unreachable
Call stack:
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
```
...

**Comment by rgrumbine** [comment]
2-3: I've updated the modules in makeall.sh and all.csh, not just to ensure listing them but to use the most recent versions available on hera.

4: That's a surprising one. Looks pretty low level inside python rather than anything from my scripts. I'm working on updating my installation.

**Comment by rgrumbine** [comment]
Can confirm that the error messages are a matter of the python installation. I've moved it to using a contributed version rather than using my own and that got rid of the messages.

**Comment by LydiaStefanova-NOAA** [comment]
Thanks Bob.
1. The modifications for 2-3 are good.
2. I am still getting the error message for 4, see log here: `/scratch1/NCEPDEV/stmp2/Lydia.B.Stefanova/LatestRestestBob/ufs-s2s-evaluation/ICE/ice_scoring/p6.verf/p6_11.err` If it is inconsequential, perhaps can be just acknowledged and ignored, at least for now? 
3. One final issue - I had accidentally omitted this in the last round of notes: When attempting to run all.csh, I get the error message `dtgfix3: Command not found.` To get it to run, I added a line in all.csh that sets `alias dtgfix3 ${path-to-mmablib}/ush/dtgfix3`. With that the code runs successfully.

**Comment by rgrumbine** [comment]
I'm glad you're checking carefully. The reason the error (in your most recent #2) didn't clear was that I hadn't removed the last reference to my old anaconda distribution. It's now gone.

I've addressed the dtgfix3 issue, temporarily at least, by giving an explicit path (for hera, at least) to mmablib, and then referencing it in the all.csh command itself. Better will be to use reliable nceplibs commands, once we find what they are.

Better still will be to use python for all.csh, as python has reliable date time commands built in. But in the transition from old (no python) to new (all python), this is my way point.

**Comment by LydiaStefanova-NOAA** [comment]
Tested, everything works, so merged. Still getting the complaints in the log: `/scratch1/NCEPDEV/stmp2/Lydia.B.Stefanova/FinalBob/ICE/p6.verf/p6_11.err` 
but that can be sorted out later if necessary.

**Review by LydiaStefanova-NOAA — COMMENTED** [review]
Code and instructions work as expected

**Pull request merged**
